[tool.poetry]
name = "obda.net"
version = "2.0.0"
description = ""
authors = ["Clemens Kaposi <clemens@kaposi.name>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1.2"
Flask-FlatPages = "^0.7.1"
Flask-Gravatar = "^0.5.0"
Pygments = "^2.6.1"
pygments-style-solarized = "^0.1.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
flake8-import-order = "^0.18.1"
fabric = "^2.5.0"

[tool.black]
line-length = 79
target-version = ["py36"]
include = "\\.(py|wsgi)$"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

