[tool.poetry]
name = "obda.net"
version = "2.0.0"
description = ""
authors = ["Clemens Kaposi <clemens@kaposi.name>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.3"
Flask-FlatPages = "^0.7.1"
Flask-Gravatar = "^0.5.0"
Pygments = "^2.12.0"

[tool.poetry.group.dev.dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
flake8-import-order = "^0.18.1"
fabric = "^2.5.0"

[tool.black]
line-length = 79
target-version = ["py310"]
include = "\\.(py|wsgi)$"
[build-system]
requires = ["poetry~=1.4.2"]
build-backend = "poetry.masonry.api"

